name: GitHub Actions Demo

run-name: ${{ github.actor }} is testing out GitHub Actions.

on: [push]

jobs:
  ls:
    runs-on: self-hosted
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Job status
      - run: echo "This job's status is ${{ job.status }}."
